name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to analyze the full commit history
      - name: Semantic Release
        uses: go-semantic-release/action@v1
        with:
          # The branch to release from
          branches: |
            main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
